fetch(url) return a promise

async function don't have an error handling method, use try{} catch(err){}